
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Aug 24 21:22:54 MDT 2010
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int GREATERTHAN = 47;
  public static final int FUNCTION = 22;
  public static final int CONST = 3;
  public static final int TWOPOINTS = 18;
  public static final int OPENSQUAREBRACKET = 20;
  public static final int CLOSESQUAREBRACKET = 21;
  public static final int NOTEQUAL = 48;
  public static final int INTEGER = 13;
  public static final int REPEAT = 30;
  public static final int MINUS = 42;
  public static final int FOR = 27;
  public static final int WRITE = 32;
  public static final int AND = 44;
  public static final int SEMICOLON = 35;
  public static final int IDENTIFICADOR = 7;
  public static final int RECORD = 5;
  public static final int TYPE = 4;
  public static final int IN = 49;
  public static final int LESSTHAN = 46;
  public static final int OR = 45;
  public static final int COMMA = 37;
  public static final int SETOF = 19;
  public static final int BEGIN = 11;
  public static final int UNTIL = 31;
  public static final int PLUS = 43;
  public static final int IF = 24;
  public static final int WRITELN = 33;
  public static final int CARET = 16;
  public static final int CLOSEPARENTHESIS = 40;
  public static final int EOF = 0;
  public static final int BOOLEAN = 14;
  public static final int EQUAL = 36;
  public static final int TRUE = 8;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int CADENA = 34;
  public static final int OPENPARENTHESIS = 39;
  public static final int COLON = 38;
  public static final int ELSE = 26;
  public static final int POINT = 15;
  public static final int TO = 28;
  public static final int THEN = 25;
  public static final int END = 12;
  public static final int ASSIGMENT = 41;
  public static final int AT = 17;
  public static final int FALSE = 9;
  public static final int VAR = 6;
  public static final int PROCEDURE = 23;
  public static final int DO = 29;
  public static final int LITERALENTERO = 10;
}

